namespace CreAtom
{
    public static class RequestTypeName
    {
        public static readonly string[] names = {
            "",
            "反 應0",
            "反 應0_解除",
            "反 應0_散播",
            "反 應0_範圍降低",
            "反 應0_範圍提昇",
            "反 應0_強度降低",
            "反 應0_強度提昇",
            "",
            "反 應1",
            "反 應1_解除",
            "反 應1_散播",
            "反 應1_範圍降低",
            "反 應1_範圍提昇",
            "反 應1_強度降低",
            "反 應1_強度提昇",
            "",
            "反 應2",
            "反 應2_解除",
            "反 應2_散播",
            "反 應2_範圍降低",
            "反 應2_範圍提昇",
            "反 應2_強度降低",
            "反 應2_強度提昇",
            "",
            "反 應3",
            "反 應3_解除",
            "反 應3_散播",
            "反 應3_範圍降低",
            "反 應3_範圍提昇",
            "反 應3_強度降低",
            "反 應3_強度提昇",
            "",
            "麻　痺",
            "麻　痺_解除",
            "麻　痺_散播",
            "麻　痺_範圍降低",
            "麻　痺_範圍提昇",
            "麻　痺_強度降低",
            "麻　痺_強度提昇",
            "",
            "帶　電",
            "帶　電_解除",
            "帶　電_散播",
            "帶　電_範圍降低",
            "帶　電_範圍提昇",
            "帶　電_強度降低",
            "帶　電_強度提昇",
            "",
            "衝　擊",
            "衝　擊_解除",
            "衝　擊_散播",
            "衝　擊_範圍降低",
            "衝　擊_範圍提昇",
            "衝　擊_強度降低",
            "衝　擊_強度提昇",
            "",
            "雷　電",
            "雷　電_解除",
            "雷　電_散播",
            "雷　電_範圍降低",
            "雷　電_範圍提昇",
            "雷　電_強度降低",
            "雷　電_強度提昇",
            "",
            "暈　眩",
            "暈　眩_解除",
            "暈　眩_散播",
            "暈　眩_範圍降低",
            "暈　眩_範圍提昇",
            "暈　眩_強度降低",
            "暈　眩_強度提昇",
            "",
            "出　血",
            "出　血_解除",
            "出　血_散播",
            "出　血_範圍降低",
            "出　血_範圍提昇",
            "出　血_強度降低",
            "出　血_強度提昇",
            "",
            "反　彈",
            "反　彈_解除",
            "反　彈_散播",
            "反　彈_範圍降低",
            "反　彈_範圍提昇",
            "反　彈_強度降低",
            "反　彈_強度提昇",
            "",
            "打　擊",
            "打　擊_解除",
            "打　擊_散播",
            "打　擊_範圍降低",
            "打　擊_範圍提昇",
            "打　擊_強度降低",
            "打　擊_強度提昇",
            "",
            "續火態",
            "續火態_解除",
            "續火態_散播",
            "續火態_範圍降低",
            "續火態_範圍提昇",
            "續火態_強度降低",
            "續火態_強度提昇",
            "",
            "燃　燒",
            "燃　燒_解除",
            "燃　燒_散播",
            "燃　燒_範圍降低",
            "燃　燒_範圍提昇",
            "燃　燒_強度降低",
            "燃　燒_強度提昇",
            "",
            "失　明",
            "失　明_解除",
            "失　明_散播",
            "失　明_範圍降低",
            "失　明_範圍提昇",
            "失　明_強度降低",
            "失　明_強度提昇",
            "",
            "灼　傷",
            "灼　傷_解除",
            "灼　傷_散播",
            "灼　傷_範圍降低",
            "灼　傷_範圍提昇",
            "灼　傷_強度降低",
            "灼　傷_強度提昇",
            "",
            "緩　慢",
            "緩　慢_解除",
            "緩　慢_散播",
            "緩　慢_範圍降低",
            "緩　慢_範圍提昇",
            "緩　慢_強度降低",
            "緩　慢_強度提昇",
            "",
            "中　毒",
            "中　毒_解除",
            "中　毒_散播",
            "中　毒_範圍降低",
            "中　毒_範圍提昇",
            "中　毒_強度降低",
            "中　毒_強度提昇",
            "",
            "冰　凍",
            "冰　凍_解除",
            "冰　凍_散播",
            "冰　凍_範圍降低",
            "冰　凍_範圍提昇",
            "冰　凍_強度降低",
            "冰　凍_強度提昇",
            "",
            "凍　傷",
            "凍　傷_解除",
            "凍　傷_散播",
            "凍　傷_範圍降低",
            "凍　傷_範圍提昇",
            "凍　傷_強度降低",
            "凍　傷_強度提昇",
            "",
            "反 應20",
            "反 應20_解除",
            "反 應20_散播",
            "反 應20_範圍降低",
            "反 應20_範圍提昇",
            "反 應20_強度降低",
            "反 應20_強度提昇",
            "",
            "反 應21",
            "反 應21_解除",
            "反 應21_散播",
            "反 應21_範圍降低",
            "反 應21_範圍提昇",
            "反 應21_強度降低",
            "反 應21_強度提昇",
            "",
            "反 應22",
            "反 應22_解除",
            "反 應22_散播",
            "反 應22_範圍降低",
            "反 應22_範圍提昇",
            "反 應22_強度降低",
            "反 應22_強度提昇",
            "",
            "反 應23",
            "反 應23_解除",
            "反 應23_散播",
            "反 應23_範圍降低",
            "反 應23_範圍提昇",
            "反 應23_強度降低",
            "反 應23_強度提昇",
            "",
            "反 應24",
            "反 應24_解除",
            "反 應24_散播",
            "反 應24_範圍降低",
            "反 應24_範圍提昇",
            "反 應24_強度降低",
            "反 應24_強度提昇",
            "",
            "反 應25",
            "反 應25_解除",
            "反 應25_散播",
            "反 應25_範圍降低",
            "反 應25_範圍提昇",
            "反 應25_強度降低",
            "反 應25_強度提昇",
            "",
            "反 應26",
            "反 應26_解除",
            "反 應26_散播",
            "反 應26_範圍降低",
            "反 應26_範圍提昇",
            "反 應26_強度降低",
            "反 應26_強度提昇",
            "",
            "反 應27",
            "反 應27_解除",
            "反 應27_散播",
            "反 應27_範圍降低",
            "反 應27_範圍提昇",
            "反 應27_強度降低",
            "反 應27_強度提昇",
            "",
            "反 應28",
            "反 應28_解除",
            "反 應28_散播",
            "反 應28_範圍降低",
            "反 應28_範圍提昇",
            "反 應28_強度降低",
            "反 應28_強度提昇",
            "",
            "反 應29",
            "反 應29_解除",
            "反 應29_散播",
            "反 應29_範圍降低",
            "反 應29_範圍提昇",
            "反 應29_強度降低",
            "反 應29_強度提昇",
            "",
            "反 應30",
            "反 應30_解除",
            "反 應30_散播",
            "反 應30_範圍降低",
            "反 應30_範圍提昇",
            "反 應30_強度降低",
            "反 應30_強度提昇",
            "",
            "反 應31",
            "反 應31_解除",
            "反 應31_散播",
            "反 應31_範圍降低",
            "反 應31_範圍提昇",
            "反 應31_強度降低",
            "反 應31_強度提昇",
        };
    }

    public enum RequestType
    {
        None = 0,
        // = 0,
        //ID0 = 1,
        //ID0_Clear = 2,
        //ID0_Spread = 3,
        //ID0_RangeDown = 4,
        //ID0_RangeUP = 5,
        //ID0_IntensityDown = 6,
        //ID0_IntensityUp = 7,
        // = 8,
        //ID1 = 9,
        //ID1_Clear = 10,
        //ID1_Spread = 11,
        //ID1_RangeDown = 12,
        //ID1_RangeUP = 13,
        //ID1_IntensityDown = 14,
        //ID1_IntensityUp = 15,
        // = 16,
        //ID2 = 17,
        //ID2_Clear = 18,
        //ID2_Spread = 19,
        //ID2_RangeDown = 20,
        //ID2_RangeUP = 21,
        //ID2_IntensityDown = 22,
        //ID2_IntensityUp = 23,
        // = 24,
        //ID3 = 25,
        //ID3_Clear = 26,
        //ID3_Spread = 27,
        //ID3_RangeDown = 28,
        //ID3_RangeUP = 29,
        //ID3_IntensityDown = 30,
        //ID3_IntensityUp = 31,
        // = 32,
        Paralysis = 33,
        Paralysis_Clear = 34,
        Paralysis_Spread = 35,
        Paralysis_RangeDown = 36,
        Paralysis_RangeUP = 37,
        Paralysis_IntensityDown = 38,
        Paralysis_IntensityUp = 39,
        // = 40,
        Electrified = 41,
        Electrified_Clear = 42,
        Electrified_Spread = 43,
        Electrified_RangeDown = 44,
        Electrified_RangeUP = 45,
        Electrified_IntensityDown = 46,
        Electrified_IntensityUp = 47,
        // = 48,
        Impact = 49,
        Impact_Clear = 50,
        Impact_Spread = 51,
        Impact_RangeDown = 52,
        Impact_RangeUP = 53,
        Impact_IntensityDown = 54,
        Impact_IntensityUp = 55,
        // = 56,
        Lightning = 57,
        Lightning_Clear = 58,
        Lightning_Spread = 59,
        Lightning_RangeDown = 60,
        Lightning_RangeUP = 61,
        Lightning_IntensityDown = 62,
        Lightning_IntensityUp = 63,
        // = 64,
        Dizzy = 65,
        Dizzy_Clear = 66,
        Dizzy_Spread = 67,
        Dizzy_RangeDown = 68,
        Dizzy_RangeUP = 69,
        Dizzy_IntensityDown = 70,
        Dizzy_IntensityUp = 71,
        // = 72,
        Bleeding = 73,
        Bleeding_Clear = 74,
        Bleeding_Spread = 75,
        Bleeding_RangeDown = 76,
        Bleeding_RangeUP = 77,
        Bleeding_IntensityDown = 78,
        Bleeding_IntensityUp = 79,
        // = 80,
        WallDeflect = 81,
        WallDeflect_Clear = 82,
        WallDeflect_Spread = 83,
        WallDeflect_RangeDown = 84,
        WallDeflect_RangeUP = 85,
        WallDeflect_IntensityDown = 86,
        WallDeflect_IntensityUp = 87,
        // = 88,
        Attack = 89,
        Attack_Clear = 90,
        Attack_Spread = 91,
        Attack_RangeDown = 92,
        Attack_RangeUP = 93,
        Attack_IntensityDown = 94,
        Attack_IntensityUp = 95,
        // = 96,
        Explosion = 97,
        Explosion_Clear = 98,
        Explosion_Spread = 99,
        Explosion_RangeDown = 100,
        Explosion_RangeUP = 101,
        Explosion_IntensityDown = 102,
        Explosion_IntensityUp = 103,
        // = 104,
        Burn = 105,
        Burn_Clear = 106,
        Burn_Spread = 107,
        Burn_RangeDown = 108,
        Burn_RangeUP = 109,
        Burn_IntensityDown = 110,
        Burn_IntensityUp = 111,
        // = 112,
        Blind = 113,
        Blind_Clear = 114,
        Blind_Spread = 115,
        Blind_RangeDown = 116,
        Blind_RangeUP = 117,
        Blind_IntensityDown = 118,
        Blind_IntensityUp = 119,
        // = 120,
        Scald = 121,
        Scald_Clear = 122,
        Scald_Spread = 123,
        Scald_RangeDown = 124,
        Scald_RangeUP = 125,
        Scald_IntensityDown = 126,
        Scald_IntensityUp = 127,
        // = 128,
        Slow = 129,
        Slow_Clear = 130,
        Slow_Spread = 131,
        Slow_RangeDown = 132,
        Slow_RangeUP = 133,
        Slow_IntensityDown = 134,
        Slow_IntensityUp = 135,
        // = 136,
        Poison = 137,
        Poison_Clear = 138,
        Poison_Spread = 139,
        Poison_RangeDown = 140,
        Poison_RangeUP = 141,
        Poison_IntensityDown = 142,
        Poison_IntensityUp = 143,
        // = 144,
        Freeze = 145,
        Freeze_Clear = 146,
        Freeze_Spread = 147,
        Freeze_RangeDown = 148,
        Freeze_RangeUP = 149,
        Freeze_IntensityDown = 150,
        Freeze_IntensityUp = 151,
        // = 152,
        Frostbite = 153,
        Frostbite_Clear = 154,
        Frostbite_Spread = 155,
        Frostbite_RangeDown = 156,
        Frostbite_RangeUP = 157,
        Frostbite_IntensityDown = 158,
        Frostbite_IntensityUp = 159,
        // = 160,
        //ID20 = 161,
        //ID20_Clear = 162,
        //ID20_Spread = 163,
        //ID20_RangeDown = 164,
        //ID20_RangeUP = 165,
        //ID20_IntensityDown = 166,
        //ID20_IntensityUp = 167,
        // = 168,
        //ID21 = 169,
        //ID21_Clear = 170,
        //ID21_Spread = 171,
        //ID21_RangeDown = 172,
        //ID21_RangeUP = 173,
        //ID21_IntensityDown = 174,
        //ID21_IntensityUp = 175,
        // = 176,
        //ID22 = 177,
        //ID22_Clear = 178,
        //ID22_Spread = 179,
        //ID22_RangeDown = 180,
        //ID22_RangeUP = 181,
        //ID22_IntensityDown = 182,
        //ID22_IntensityUp = 183,
        // = 184,
        //ID23 = 185,
        //ID23_Clear = 186,
        //ID23_Spread = 187,
        //ID23_RangeDown = 188,
        //ID23_RangeUP = 189,
        //ID23_IntensityDown = 190,
        //ID23_IntensityUp = 191,
        // = 192,
        //ID24 = 193,
        //ID24_Clear = 194,
        //ID24_Spread = 195,
        //ID24_RangeDown = 196,
        //ID24_RangeUP = 197,
        //ID24_IntensityDown = 198,
        //ID24_IntensityUp = 199,
        // = 200,
        //ID25 = 201,
        //ID25_Clear = 202,
        //ID25_Spread = 203,
        //ID25_RangeDown = 204,
        //ID25_RangeUP = 205,
        //ID25_IntensityDown = 206,
        //ID25_IntensityUp = 207,
        // = 208,
        //ID26 = 209,
        //ID26_Clear = 210,
        //ID26_Spread = 211,
        //ID26_RangeDown = 212,
        //ID26_RangeUP = 213,
        //ID26_IntensityDown = 214,
        //ID26_IntensityUp = 215,
        // = 216,
        //ID27 = 217,
        //ID27_Clear = 218,
        //ID27_Spread = 219,
        //ID27_RangeDown = 220,
        //ID27_RangeUP = 221,
        //ID27_IntensityDown = 222,
        //ID27_IntensityUp = 223,
        // = 224,
        //ID28 = 225,
        //ID28_Clear = 226,
        //ID28_Spread = 227,
        //ID28_RangeDown = 228,
        //ID28_RangeUP = 229,
        //ID28_IntensityDown = 230,
        //ID28_IntensityUp = 231,
        // = 232,
        //ID29 = 233,
        //ID29_Clear = 234,
        //ID29_Spread = 235,
        //ID29_RangeDown = 236,
        //ID29_RangeUP = 237,
        //ID29_IntensityDown = 238,
        //ID29_IntensityUp = 239,
        // = 240,
        //ID30 = 241,
        //ID30_Clear = 242,
        //ID30_Spread = 243,
        //ID30_RangeDown = 244,
        //ID30_RangeUP = 245,
        //ID30_IntensityDown = 246,
        //ID30_IntensityUp = 247,
        // = 248,
        //ID31 = 249,
        //ID31_Clear = 250,
        //ID31_Spread = 251,
        //ID31_RangeDown = 252,
        //ID31_RangeUP = 253,
        //ID31_IntensityDown = 254,
        //ID31_IntensityUp = 255,

        Count,
    }
}